export const categories = [
  {
    id: "bread",
    name: "Bread",
    image: "/images/bread.png",
    items: [
      "Whole Wheat Bread",
      "Rye Bread",
      "Baguette",
      "Sourdough",
      "Multigrain",
      "Gluten-Free Bread",
      "White Bread",
    ],
  },
  {
    id: "milk",
    name: "Milk",
    image: "/images/milk.png",
    items: [
      "Whole Milk",
      "Skim Milk",
      "Soy Milk",
      "Almond Milk",
      "Oat Milk",
      "Lactose-Free Milk",
      "Coconut Milk",
    ],
  },
  {
    id: "fruit",
    name: "Fruit",
    image: "/images/fruit.png",
    items: [
      "Apples",
      "Bananas",
      "Oranges",
      "Grapes",
      "Berries",
      "Melons",
      "Kiwis",
    ],
  },
  {
    id: "cheese",
    name: "Cheese",
    image: "/images/cheese.png",
    items: [
      "Cheddar",
      "Mozzarella",
      "Feta",
      "Swiss",
      "Gouda",
      "Brie",
      "Cottage Cheese",
    ],
  },
  {
    id: "veggies",
    name: "Veggies",
    image: "/images/veggies.png",
    items: [
      "Carrots",
      "Broccoli",
      "Spinach",
      "Peppers",
      "Tomatoes",
      "Onions",
      "Cucumbers",
    ],
  },
  {
    id: "meat",
    name: "Meat",
    image: "/images/meat.png",
    items: [
      "Chicken",
      "Beef",
      "Pork",
      "Turkey",
      "Sausage",
      "Ham",
      "Lamb",
    ],
  },
  {
    id: "eggs",
    name: "Eggs",
    image: "/images/eggs.png",
    items: [
      "Free Range Eggs",
      "Organic Eggs",
      "Brown Eggs",
      "White Eggs",
      "Large Eggs",
      "Medium Eggs",
      "Quail Eggs",
    ],
  },
];
